name = "medium-backend"
compatibility_date = "2024-08-21"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjEyYTgxZjgtMDdkNi00ZmMwLWEwN2QtZDNkYWM5YjM2ODE3IiwidGVuYW50X2lkIjoiZGQ5OGU4OWQxYWQxNWIxZDg0Nzc1M2U0ZDgwNmNkMGMwM2I1NDAxYWQzNDc5YWFkNjJjOWI2NzllZDVlNTA1YyIsImludGVybmFsX3NlY3JldCI6ImI1YzY4N2I2LTA1NDAtNDAzNC05YWVlLTc0ZTFlZTg2NWNhYiJ9.OR7ulbhAacZS0efMkUCb89SZSORyE07W0ADMjUaDpg0"
