version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb123"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  backend:
    image: "mongo_app"
    container_name: backend_application
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongodb123:27017
volumes:
  mongodb_data:
